# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-11-05 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid1', models.IntegerField(verbose_name='用户自身id')),
                ('uid2', models.IntegerField(verbose_name='好友id')),
            ],
        ),
        migrations.CreateModel(
            name='Swiped',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(verbose_name='用户自身id')),
                ('sid', models.IntegerField(verbose_name='被滑的陌生人id')),
                ('mark', models.CharField(choices=[('dislike', 'dislike'), ('like', 'like'), ('superlike', 'superlike')], max_length=10, verbose_name='滑动类型')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='滑动的时间')),
            ],
        ),
    ]
